from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_ipprefix_tree", "0001_add_extensions"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS netbox_ipprefix_tree_hierarchy (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                parent_prefix_id BIGINT NOT NULL
                    REFERENCES ipam_prefix(id)
                    ON DELETE CASCADE,

                child_prefix_id BIGINT NOT NULL
                    REFERENCES ipam_prefix(id)
                    ON DELETE CASCADE,

                vrf_id BIGINT NULL
                    REFERENCES ipam_vrf(id)
                    ON DELETE CASCADE,

                created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS netbox_ipprefix_tree_hierarchy;
            """,
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS netbox_ipprefix_tree_rebuild_state (
                id INTEGER PRIMARY KEY DEFAULT 1,

                dirty BOOLEAN NOT NULL DEFAULT TRUE,

                rebuilding BOOLEAN NOT NULL DEFAULT FALSE,

                last_rebuild TIMESTAMP WITH TIME ZONE NULL,

                updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),

                CONSTRAINT netbox_ipprefix_tree_rebuild_state_singleton
                    CHECK (id = 1)
            );
            """,
            reverse_sql="""
            DROP TABLE IF EXISTS netbox_ipprefix_tree_rebuild_state;
            """,
        ),
        migrations.RunSQL(
            sql="""
            INSERT INTO netbox_ipprefix_tree_rebuild_state (
                id,
                dirty,
                rebuilding,
                last_rebuild,
                updated
            )
            VALUES (
                1,
                TRUE,
                FALSE,
                NULL,
                now()
            )
            ON CONFLICT (id) DO NOTHING;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
