from django.core.management.base import BaseCommand
from django.db import connection, transaction


ADVISORY_LOCK_ID = 847362819


class Command(BaseCommand):
    help = "Rebuild prefix hierarchy table"

    def add_arguments(self, parser):
        parser.add_argument(
            "--force",
            action="store_true",
            help="Force rebuild even if the hierarchy is not marked dirty",
        )

    def handle(self, *args, **options):

        force = options["force"]

        with connection.cursor() as cursor:
            cursor.execute(
                "SELECT pg_try_advisory_lock(%s)",
                [ADVISORY_LOCK_ID],
            )

            locked = cursor.fetchone()[0]

        if not locked:
            self.stdout.write(
                self.style.WARNING(
                    "Another prefix hierarchy rebuild is already running"
                )
            )
            return

        rebuild_started = False

        try:
            if force:
                rebuild_started = self._force_rebuild_ownership()
            else:
                rebuild_started = self._acquire_rebuild_ownership()

            if not rebuild_started:
                self.stdout.write(
                    self.style.SUCCESS("No prefix hierarchy rebuild required")
                )
                return

            self.stdout.write("Building replacement prefix hierarchy table...")

            self._build_replacement_table()

            self.stdout.write("Creating replacement hierarchy indexes...")

            self._create_replacement_indexes()

            self.stdout.write("Swapping replacement hierarchy table into place...")

            self._swap_replacement_table()

            self._mark_rebuild_complete()

            self.stdout.write(self.style.SUCCESS("Prefix hierarchy rebuild completed"))

        except Exception:
            self._mark_rebuild_failed()
            raise

        finally:
            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT pg_advisory_unlock(%s)",
                    [ADVISORY_LOCK_ID],
                )

    def _acquire_rebuild_ownership(self):
        """
        Mark this process as the active rebuilder only if the hierarchy is dirty
        and no other rebuild is currently marked as running.
        """

        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE
                    netbox_ipprefix_tree_rebuild_state
                SET
                    rebuilding = TRUE,
                    updated = now()
                WHERE
                    id = 1
                    AND dirty = TRUE
                    AND rebuilding = FALSE
                RETURNING id
                """
            )

            row = cursor.fetchone()

        return row is not None

    def _force_rebuild_ownership(self):
        """
        Force a rebuild regardless of the dirty flag.

        The advisory lock already prevents two rebuild commands from running
        concurrently, but the rebuilding flag is still updated so the state table
        reflects what is happening.
        """

        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE
                    netbox_ipprefix_tree_rebuild_state
                SET
                    dirty = TRUE,
                    rebuilding = TRUE,
                    updated = now()
                WHERE
                    id = 1
                RETURNING id
                """
            )

            row = cursor.fetchone()

        return row is not None

    def _build_replacement_table(self):
        """
        Build the replacement hierarchy table.

        The table is built separately so the existing live hierarchy remains
        available while the expensive hierarchy calculation is running.
        """

        with connection.cursor() as cursor:
            cursor.execute(
                """
                DROP TABLE IF EXISTS
                    netbox_ipprefix_tree_hierarchy_new
                CASCADE
                """
            )

            cursor.execute(
                """
                CREATE TABLE
                    netbox_ipprefix_tree_hierarchy_new
                (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                    parent_prefix_id BIGINT NOT NULL
                        REFERENCES ipam_prefix(id)
                        ON DELETE CASCADE,

                    child_prefix_id BIGINT NOT NULL
                        REFERENCES ipam_prefix(id)
                        ON DELETE CASCADE,

                    vrf_id BIGINT NULL
                        REFERENCES ipam_vrf(id)
                        ON DELETE CASCADE,

                    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
                )
                """
            )

            cursor.execute(
                """
                INSERT INTO
                    netbox_ipprefix_tree_hierarchy_new (
                        parent_prefix_id,
                        child_prefix_id,
                        vrf_id
                    )
                SELECT
                    parent.id,
                    child.id,
                    child.vrf_id
                FROM ipam_prefix child
                JOIN LATERAL (
                    SELECT
                        p.id
                    FROM ipam_prefix p
                    WHERE
                        p.id != child.id
                        AND child.prefix <<= p.prefix
                        AND masklen(p.prefix) < masklen(child.prefix)
                        AND (
                            (
                                child.vrf_id IS NULL
                                AND p.vrf_id IS NULL
                            )
                            OR
                            (
                                child.vrf_id = p.vrf_id
                            )
                        )
                    ORDER BY
                        masklen(p.prefix) DESC
                    LIMIT 1
                ) parent
                    ON TRUE
                """
            )

    def _create_replacement_indexes(self):
        """
        Create indexes on the replacement table before the swap.

        Temporary index names are used so they do not collide with the live
        table's current index names. During the swap, these indexes are renamed
        to the final production names.
        """

        with connection.cursor() as cursor:
            cursor.execute(
                """
                CREATE INDEX
                    netbox_ipprefix_tree_hierarchy_parent_child_idx_new
                ON netbox_ipprefix_tree_hierarchy_new (
                    parent_prefix_id,
                    child_prefix_id
                )
                """
            )

            cursor.execute(
                """
                CREATE UNIQUE INDEX
                    netbox_ipprefix_tree_hierarchy_child_unique_idx_new
                ON netbox_ipprefix_tree_hierarchy_new (
                    child_prefix_id
                )
                """
            )

    def _swap_replacement_table(self):
        """
        Atomically swap the replacement hierarchy table into place.

        The expensive work is done before this point. This transaction should be
        short: rename live table, rename replacement table, drop old table, and
        rename the replacement indexes.
        """

        with transaction.atomic():
            with connection.cursor() as cursor:
                cursor.execute(
                    """
                    DROP TABLE IF EXISTS
                        netbox_ipprefix_tree_hierarchy_old
                    CASCADE
                    """
                )

                cursor.execute(
                    """
                    ALTER TABLE
                        netbox_ipprefix_tree_hierarchy
                    RENAME TO
                        netbox_ipprefix_tree_hierarchy_old
                    """
                )

                cursor.execute(
                    """
                    ALTER TABLE
                        netbox_ipprefix_tree_hierarchy_new
                    RENAME TO
                        netbox_ipprefix_tree_hierarchy
                    """
                )

                cursor.execute(
                    """
                    DROP TABLE
                        netbox_ipprefix_tree_hierarchy_old
                    CASCADE
                    """
                )

                cursor.execute(
                    """
                    ALTER INDEX
                        netbox_ipprefix_tree_hierarchy_parent_child_idx_new
                    RENAME TO
                        netbox_ipprefix_tree_hierarchy_parent_child_idx
                    """
                )

                cursor.execute(
                    """
                    ALTER INDEX
                        netbox_ipprefix_tree_hierarchy_child_unique_idx_new
                    RENAME TO
                        netbox_ipprefix_tree_hierarchy_child_unique_idx
                    """
                )

    def _mark_rebuild_complete(self):
        """
        Mark the rebuild as complete.

        If prefixes changed during the rebuild, a database trigger may have set
        dirty = TRUE while rebuilding was TRUE. This update intentionally sets
        dirty = FALSE, matching your current operational model where the rebuild
        represents the completed snapshot at the time the replacement table was
        built.
        """

        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE
                    netbox_ipprefix_tree_rebuild_state
                SET
                    dirty = FALSE,
                    rebuilding = FALSE,
                    last_rebuild = now(),
                    updated = now()
                WHERE
                    id = 1
                """
            )

    def _mark_rebuild_failed(self):
        """
        Clear the rebuilding flag after failure.

        The dirty flag is intentionally left TRUE so another rebuild can be
        attempted later.
        """

        with connection.cursor() as cursor:
            cursor.execute(
                """
                UPDATE
                    netbox_ipprefix_tree_rebuild_state
                SET
                    rebuilding = FALSE,
                    updated = now()
                WHERE
                    id = 1
                """
            )
